### ISSUE TITLE
Turn on GitHub Wiki feature

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#163]
While the `wiki/` folder is designed to work as standalone in-source documentation, the links (like the ones in the readme) assume that there is a https://github.com/devcontainers-contrib/features/wiki. This requires turning on the GitHub Wiki in the Settings tab. It will auto-publish using a GitHub Action.

https://github.com/devcontainers-contrib/features/actions/workflows/Publish%20the%20dev%20wiki.yml
```yml
on:
  push:
    branches: [main]
    paths: [wiki/**, .github/workflows/Publish the dev wiki.yml]
# ...
```

@danielbraun89 is the only one with access to do this (I think)
